.gitignore
sunsu-wedding/.idea/misc.xml
sunsu-wedding/build.gradle
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/errors/BaseException.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/security/CustomCoupleDetails.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/security/CustomPlannerDetails.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/security/CustomUserDetailsService.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/security/JWTProvider.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/security/JwtAuthenticationFilter.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/security/SecurityConfig.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/Grade.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/UserRequest.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/UserResponse.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/UserRestController.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/UserService.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/constant/Grade.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/constant/Role.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/couple/Couple.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/couple/CoupleJPARepository.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/planner/Planner.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/planner/PlannerJPARepository.java
sunsu-wedding/src/test/java/com/kakao/sunsuwedding/_core/DummyEntity.java
sunsu-wedding/src/test/java/com/kakao/sunsuwedding/user/CoupleJPARepositoryTest.java
sunsu-wedding/src/test/java/com/kakao/sunsuwedding/user/PlannerJPARepositoryTest.java
sunsu-wedding/src/test/java/com/kakao/sunsuwedding/user/UserRestControllerTest.java

- 회원가입 기능 & 테스트(Repository, Controller)
- 스프링 시큐리티
> 인증 및 권한 부분을 작성했는데 제대로 작동할지 확실하지 않아서 추후 검증이 필요할 것 같습니다  
> 빠진 부분 있으면 말해주세용
```java
http.authorizeHttpRequests((authorizeHttpRequests) ->
authorizeHttpRequests
.requestMatchers(
new AntPathRequestMatcher("/user/signup"),
new AntPathRequestMatcher("/user/login"),
new AntPathRequestMatcher("/portfolios/**", "GET")
).permitAll()
.requestMatchers(
new AntPathRequestMatcher("/user/**"),
new AntPathRequestMatcher("/portfolios/**"),
new AntPathRequestMatcher("/chat/**"),
new AntPathRequestMatcher("/quotations/**")
).authenticated()
// 검증 필요
.requestMatchers(
new AntPathRequestMatcher("/chat", "POST"),
new AntPathRequestMatcher("/quotations/confirmAll/**", "POST"),
new AntPathRequestMatcher("/payments", "POST")
).hasRole("COUPLE") …
```

회원가입 및 시큐리티 구현

---

README.md

README 파일에 실행 방법 재작성

---

.github/workflows/spring-boot-ci.yml
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/Match.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/MatchJPARepository.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/Quotation/Quotation.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/Quotation/QuotationJPARepository.java
sunsu-wedding/src/test/java/com/kakao/sunsuwedding/user/UserRestControllerTest.java

- 회원 탈퇴 구현에 필요해서 Match, Quotation의 엔티티 작성 및 레포지토리 생성
- userController에서 회원 탈퇴 api 매핑 및 메서드 작성
- userService에서 회원 탈퇴 메서드 스켈레톤 코드 작성 
- 멘토링 후에 견적서, 매칭내역 어떻게 처리할 지 정해지면 완성시키겠습니다!
close #21

회원 탈퇴 기능 기본 구현

---

README.md
sunsu-wedding/src/test/java/com/kakao/sunsuwedding/portfolio/PortfolioControllerTest.java

- 이미지 저장 경로 문제로 석준님 로컬에서만 통과하는 테스트 코드를 주석 처리했습니다(이후 PR시 원활한 Github CI 사용을 위해..)
- readme 파일에 팀원 소개를 추가하고 카카오에서 만들어준 default README 내용을 토글로 변경했습니다.

실패하는 테스트 코드 주석 처리

---

sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/Portfolio.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/UserRequest.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/UserService.java
sunsu-wedding/src/main/resources/db/teardown.sql
sunsu-wedding/src/test/java/com/kakao/sunsuwedding/user/UserRestControllerTest.java

- 로그인 DTO에서 role 삭제, 관련 코드 수정
- userService 내의 탈퇴 코드 간략화
- Portfolio에 DeleteAction 추가
- teardown.sql에 raw password 주석으로 추가
close #40

로그인, 회원가입 관련 리팩토링

---

LICENSE

chore: Add MIT LICENSE

---

LICENSE
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/errors/BaseException.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/Match.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/Quotation/Quotation.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/Quotation/QuotationDTOConverter.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/Quotation/QuotationRequest.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/Quotation/QuotationResponse.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/Quotation/QuotationRestController.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/Quotation/QuotationService.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/Quotation/QuotationStatus.java
sunsu-wedding/src/main/resources/db/teardown.sql
sunsu-wedding/src/test/java/com/kakao/sunsuwedding/quotation/QuotationRepositoryTest.java

- 견적서 생성 및 조회 기능 구현
- close #50

견적서 조회, 생성 기능 구현

---

sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/Quotation/Quotation.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/Quotation/QuotationDTOConverter.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/Quotation/QuotationResponse.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/Quotation/QuotationService.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/Quotation/QuotationStatus.java
sunsu-wedding/src/main/resources/db/teardown.sql

- enum 타입 지정 잘못해서 teardown.sql에서 오류가 발생하는 오류를 수정했습니다 ..!!

fix: enum type error

---

sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/errors/BaseException.java

- BaseException 파일이 빠져 추가합니다,,!

BaseException 파일 추가

---

sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/Match.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/MatchRequest.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/MatchRestController.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/MatchService.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/Quotation/QuotationService.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/image/ImageItemService.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/UserResponse.java
sunsu-wedding/src/main/resources/db/teardown.sql
sunsu-wedding/src/test/java/com/kakao/sunsuwedding/user/CoupleJPARepositoryTest.java
sunsu-wedding/src/test/java/com/kakao/sunsuwedding/user/PlannerJPARepositoryTest.java
sunsu-wedding/src/test/java/com/kakao/sunsuwedding/user/UserJPARepositoryTest.java
sunsu-wedding/src/test/java/com/kakao/sunsuwedding/user/UserRestControllerTest.java

채팅방 생성 및 기타 에러 해결

---

sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/Match.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/Portfolio.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/PortfolioJPARepository.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/PortfolioService.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/image/ImageItem.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/price/PriceItem.java

- Portfolio 엔티티에 is_active 컬럼 추가
- @SQLDelete와 @Where 어노테이션에 is_active 컬럼을 바인딩하여
- DELETE 시 Soft_delete가 작동하도록 구현

포트폴리오 SOFT DELETE 처리 로직 구현

---

sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/security/JWTProvider.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/security/JwtAuthenticationFilter.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/security/SecurityConfig.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/UserRestController.java
sunsu-wedding/src/test/java/com/kakao/sunsuwedding/quotation/QuotationRestControllerTest.java
sunsu-wedding/src/test/java/com/kakao/sunsuwedding/user/UserRestControllerTest.java

JWTProvider 변수 non-static으로 변경

---

sunsu-wedding/build.gradle
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/payment/Payment.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/payment/PaymentRequest.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/payment/PaymentRestController.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/payment/PaymentService.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/payment/TossPaymentResponse.java
sunsu-wedding/src/test/java/com/kakao/sunsuwedding/payment/PaymentRestControllerTest.java

- 결제 정보 저장시 paymentKey 삭제하기
- 검증: 프론트 정보와 백엔드 정보 비교
- 토스페이먼츠 승인 요청
- 유저 업그레이드
- 결제 관련 정보 저장
- paymentRepository Test
- 나머지 결제 관련 api 삭제

결제 통합 승인 API 구현

---

sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/MatchDTOConverter.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/MatchResponse.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/MatchService.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/quotation/QuotationDTOConverter.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/quotation/QuotationResponse.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/ReviewDTOConverter.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/ReviewJPARepository.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/ReviewRequest.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/ReviewResponse.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/ReviewRestController.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/ReviewService.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/UserService.java
sunsu-wedding/src/test/java/com/kakao/sunsuwedding/review/ReviewRestControllerTest.java

-  플래너 리뷰 전체 조회하기 (포트폴리오에 이용)
- 플래너 리뷰 조회 페이지네이션 구현
- 리뷰 상세 조회 기능 구현
- 리뷰 모아보기 - 공통기능에서 예비부부 기능으로 분리
- 기타 자잘한 리팩토링 
- 견적서 모아보기 페이지네이션
- 견적서 모아보기 정렬 조건
close #135

리뷰 기능 수정 및 페이지네이션 구현

---

sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/Match.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/PortfolioRestController.java
sunsu-wedding/src/test/java/com/kakao/sunsuwedding/_core/DummyEntity.java
sunsu-wedding/src/test/java/com/kakao/sunsuwedding/match/MatchRepositoryTest.java
sunsu-wedding/src/test/java/com/kakao/sunsuwedding/portfolio/image/ImageItemJPARepositoryTest.java
sunsu-wedding/src/test/java/com/kakao/sunsuwedding/portfolio/price/PriceItemJPARepositoryTest.java
sunsu-wedding/src/test/java/com/kakao/sunsuwedding/util/PriceCalculatorTest.java

- 이미지 JPARepository 테스트
- 가격 JPARepository 테스트
- PriceCalculator  테스트
close #147

이미지, 가격 JPARepository, PriceCalculator 테스트코드 작성

---

sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/MatchRestController.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/MatchService.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/PortfolioRestController.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/PortfolioService.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/quotation/QuotationRestController.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/quotation/QuotationService.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/ReviewRestController.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/ReviewService.java
sunsu-wedding/src/test/java/com/kakao/sunsuwedding/portfolio/PortfolioControllerTest.java
sunsu-wedding/src/test/java/com/kakao/sunsuwedding/review/ReviewRestControllerTest.java

> 전체 패키지의 Controller, Service 메서드명 일관성 있게 통일
(회원가입, 로그인 등 특정 의미가 있는 단어 제외)
> C : `add{단수명사}`, ex) `addMatch`
> R (한개) : `find{단수명사}By{조건}` ex) `findMatchById`
> R (여러개) : `find{복수명사}By{조건}` ex) `findMatchesByChatId`
> U : `update{단수명사}` ex) `updateMatch`
> D : `delete{단수명사}` ex) `deleteMatch`
close #161

Controller, Service 메서드명 통일

---

sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/config/SecurityConfig.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/favorite/FavoriteDTOConverter.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/favorite/FavoriteResponse.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/favorite/FavoriteRestController.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/MatchRestController.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/MatchService.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/match/MatchServiceImpl.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/payment/PaymentRestController.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/PortfolioRestController.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/quotation/QuotationRestController.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/ReviewRestController.java
sunsu-wedding/src/test/java/com/kakao/sunsuwedding/favorite/FavoriteRestControllerTest.java
sunsu-wedding/src/test/java/com/kakao/sunsuwedding/match/MatchRestControllerTest.java
sunsu-wedding/src/test/java/com/kakao/sunsuwedding/payment/PaymentRestControllerTest.java
sunsu-wedding/src/test/java/com/kakao/sunsuwedding/portfolio/PortfolioControllerTest.java
sunsu-wedding/src/test/java/com/kakao/sunsuwedding/quotation/QuotationRestControllerTest.java
sunsu-wedding/src/test/java/com/kakao/sunsuwedding/review/ReviewRestControllerTest.java

- 복수형 → 단수형 변경 (결제, 포트폴리오, 견적서, 리뷰, 찜하기)
- 견적서 전체 모아보기, 리뷰 전체 모아보기: /collect → /all
- 견적서 전체 확정 /confirmAll → /confirm
- 모아보기에 별점 추가
- 메일 내용 추가 및 변경된 엔드 포인트 적용
close #160

엔드포인트 변경 및 찜하기 별점 추가

---

sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/config/SecurityConfig.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/constants/Constants.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/errors/exception/BadRequestException.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/errors/exception/ForbiddenException.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/errors/exception/NotFoundException.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/errors/exception/ServerException.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/errors/exception/UnauthorizedException.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/security/JwtAuthenticationFilter.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/utils/UserDataChecker.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/PortfolioRestController.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/quotation/QuotationRestController.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/ReviewServiceImpl.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/UserRestController.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/UserService.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/UserServiceImpl.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/email/EmailCodeRestController.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/email/EmailRequest.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/email/EmailServiceImpl.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/token/TokenService.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/token/TokenServiceImpl.java
sunsu-wedding/src/test/java/com/kakao/sunsuwedding/chat/ChatControllerTest.java
sunsu-wedding/src/test/java/com/kakao/sunsuwedding/favorite/FavoriteRestControllerTest.java
sunsu-wedding/src/test/java/com/kakao/sunsuwedding/match/MatchRestControllerTest.java
sunsu-wedding/src/test/java/com/kakao/sunsuwedding/payment/PaymentRestControllerTest.java
sunsu-wedding/src/test/java/com/kakao/sunsuwedding/portfolio/PortfolioControllerTest.java
sunsu-wedding/src/test/java/com/kakao/sunsuwedding/quotation/QuotationRestControllerTest.java
sunsu-wedding/src/test/java/com/kakao/sunsuwedding/review/ReviewRestControllerTest.java
sunsu-wedding/src/test/java/com/kakao/sunsuwedding/user/UserRestControllerTest.java

- GET /api/portfolio 요청 시 access token이 있다면 검증하도록 수정
- (안쓰지만 .... 그래도 .... ) 이메일 요청 DTO 제약조건 추가
- 메서드명 리팩토링
- cors 설정 변경
close #172

CORS 설정, 토큰 검증 API 추가, DTO 제약조건 추가, 리팩토링

---

sunsu-wedding/src/main/java/com/kakao/sunsuwedding/quotation/QuotationDTOConverter.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/quotation/QuotationResponse.java

- 견적서 모아보기의 modifiedAt 자료형을 string으로 변경
한 번에 하려다가,,, 멋진 백엔드 분들이 다 해주셔서,, 저는 이것만 날립니닷....

DTO modifiedAt 자료형 변경

---

sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/errors/BaseException.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/errors/GlobalExceptionHandler.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/security/JwtAuthenticationFilter.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/utils/UserDataChecker.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/PortfolioRestController.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/PortfolioServiceImpl.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/PortfolioSpecification.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/UserServiceImpl.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/email/EmailServiceImpl.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/token/TokenServiceImpl.java
sunsu-wedding/src/main/resources/db/teardown.sql

- GET /api/portfolio 의 모든 요청에서 토큰이 존재한다면 검증하도록 수정
- 쿼리 스트링으로 들어오는 데이터의 타입이 일치하지 않을 경우 발생하는 에러 메시지 수정
- 자잘한 코드 리팩토링 ...
close #176
close #177
빠이팅입니다 !

토큰 에러 검출 api 추가, 에러 메시지 내용 수정

---

sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/ReviewRequest.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/ReviewRestController.java
sunsu-wedding/src/test/java/com/kakao/sunsuwedding/review/ReviewRestControllerTest.java

- 특정 플래너 리뷰 모아보기 API 변경
기존 API `/api/review?page={page}` -> 변경된 API `/api/review?page={page}&plannerId={plannerId}`
- 더 이상 사용되지 않는 FindAllByPlannerDTO 삭제
- 변경사항에 따라 find_review_by_planner_success_test 테스트 코드 수정

특정 플래너 리뷰 모아보기 API 수정

---

sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/config/SecurityConfig.java

플래너별 리뷰 조회 권한 설정

---

sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/errors/BaseException.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/errors/GlobalExceptionHandler.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/security/CustomUserDetailsService.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/security/JWTProvider.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/utils/UserDataChecker.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/Review.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/ReviewServiceImpl.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/base_user/User.java
sunsu-wedding/src/test/java/com/kakao/sunsuwedding/portfolio/PortfolioControllerTest.java

- 유저 및 리뷰 테이블의 유니크 제약조건 변경
- 잘못 리팩토링된 메서드 롤백
close #183

유저 및 리뷰 테이블의 유니크 제약조건 변경

---

sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/ReviewServiceImpl.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/image/ReviewImageItemJPARepository.java

- find 네임쿼리에 All를 빼먹은 오타 수정 
- ex) `findByReviewMatchCoupleId -> findAllByReviewMatchCoupleId `

리뷰 이미지 조회 쿼리 오타 수정

---

sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/errors/BaseException.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/quotation/QuotationServiceImpl.java

- 탈퇴한 유저와의 매칭에서 견적서를 추가할 수 있는 버그 수정

탈퇴한 유저 견적서 추가 버그 수정

---

sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/utils/PriceCalculator.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/payment/PaymentRequest.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/Portfolio.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/PortfolioDTOConverter.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/PortfolioRequest.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/portfolio/PortfolioServiceImpl.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/quotation/Quotation.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/review/Review.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/UserRequest.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/user/base_user/User.java
sunsu-wedding/src/test/java/com/kakao/sunsuwedding/portfolio/PortfolioControllerTest.java

- Request Body에 길이 제약 조건 추가
- 엔티티에 길이 제약 조건 추가
- 포트폴리오 없는데 삭제시 에러 메시지 추가

Request Body에 길이 제약 조건 추가

---

sunsu-wedding/src/main/java/com/kakao/sunsuwedding/_core/config/SecurityConfig.java
sunsu-wedding/src/main/java/com/kakao/sunsuwedding/payment/PaymentServiceImpl.java
sunsu-wedding/src/main/resources/application-prod.yml

- 토스 페이먼츠 프록시 설정
- application-prod.yml 파일 추가

토스페이먼츠 프록시 설정
